import Head from "next/head";
import Styles from "@/styles/Home.module.css";
import { TabList } from "@/components/TabList";
import { TasksContext } from "@/contexts/tasks";
import { useEffect, useState } from "react";
import { Storage } from "@/libs/localStorage";

export default function Home() {
  const [data, setData] = useState<Tab[]>([]);
  const [isMobile, setIsMobile] = useState(false);

  const handleResize = () => {
    setIsMobile(window.innerWidth < 600);
  };
  useEffect(() => {
    setData(Storage.get());
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);
  return (
    <TasksContext value={{ data, setData, isMobile }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabList tabs={data} />
    </TasksContext>
  );
}
