import Head from "next/head";
import styles from "../styles/Home.module.css";
import { TabList } from "../components/TabList";
import { TasksContext } from "../contexts/tasks";
import { useState } from "react";
import { Storage } from "../libs/localStorage";

export default function Home() {
  const [data, setData] = useState(Storage.get());
  return (
    <TasksContext value={{ data, setData }}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <TabList tabs={data} />
    </TasksContext>
  );
}
