import Head from "next/head";
import styles from "../styles/Home.module.css";
import { TabList } from "../components/TabList";
import { TasksContext } from "../contexts/tasks";
import { useLayoutEffect, useState } from "react";
import { Storage } from "../libs/localStorage";

export default function Home() {
  const [data, setData] = useState(Storage.get());
  const [isMobile, setIsMobile] = useState(window?.innerWidth > 600);

  const handleResize = () => {
    setIsMobile(window.innerWidth > 600);
  };
  useLayoutEffect(() => {
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);
  return (
    <TasksContext value={{ data, setData, isMobile }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabList tabs={data} />
    </TasksContext>
  );
}
